###Ways of creating Arrays in Numpy###

#array()    
#linspace()    
#logspace()    
#arange()    
#zeros()    
#ones()    

In [13]:
from numpy import*

arr = array([1,2,3,4,5,6])

print(arr)

[1 2 3 4 5 6]


In [14]:
from numpy import*

arr = array([1,2,3,4,5,6])

print(arr.dtype)

int32


In [15]:
from numpy import*

arr = array([1,2,3.0,4,5,6])

print(arr)

[1. 2. 3. 4. 5. 6.]


In [16]:
from numpy import*

arr = array([1,2,3.0,4,5,6])

print(arr.dtype)

float64


In [17]:
from numpy import*

arr = array([1,2,3,4,5,6],float)

print(arr)

[1. 2. 3. 4. 5. 6.]


In [18]:
#linspace(a,b,c) a is start, b is end, and c is number of steps to break the array.

arr = linspace(2,20,10)
print(arr)

[ 2.  4.  6.  8. 10. 12. 14. 16. 18. 20.]


In [19]:
#if steps not mentioned then it breaks range in to 50 parts.

arr = linspace(0,10)
print(arr)

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]


In [22]:
arr = linspace(1,10,20)
print(arr)


[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


In [23]:
arr = arange(2,20,2)
print(arr)

[ 2  4  6  8 10 12 14 16 18]


In [32]:
arr = logspace(1,40,5)
print('%.2f'%arr[0])

10.00


In [33]:
arr = logspace(1,40,5)
print('%.2f'%arr[3])

1778279410038922838185969975296.00


In [34]:
arr = logspace(1,40,5)
print('%.2f'%arr[4])

10000000000000000303786028427003666890752.00


In [36]:
arr = zeros(5)
print(arr)

[0. 0. 0. 0. 0.]


In [38]:
arr = ones(7,int)
print(arr)

[1 1 1 1 1 1 1]
