Copying Array in Python

In [1]:
from numpy import*

arr = array([1,2,3,4,5])

print(arr)

[1 2 3 4 5]


In [4]:
arr = array([1,2,3,4,5])
arr = arr + 5
print(arr)

[ 6  7  8  9 10]


In [20]:
arr1 = array([1,2,3,4,5])
arr2 = array([5,6,7,8,9])

print(arr1 + arr2)

[ 6  8 10 12 14]


In [6]:
arr = array([1,2,3,4,5])
print(sin(arr))

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


In [8]:
arr = array([1,2,3,4,5])
print(cos(arr))

[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]


In [9]:
arr = array([1,2,3,4,5])
print(log(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [10]:
arr = array([1,2,3,4,5])
print(sqrt(arr))

[1.         1.41421356 1.73205081 2.         2.23606798]


In [11]:
arr = array([1,2,3,4,5])
print(sum(arr))

15


In [12]:
print(min(arr))

1


In [13]:
print(max(arr))

5


In [21]:
print(concatenate([arr1,arr2]))

[1 2 3 4 5 5 6 7 8 9]


In [23]:
# copying array

arr1 = arr2

print(arr1)
print(arr2)

print(id(arr1))
print(id(arr2))

[5 6 7 8 9]
[5 6 7 8 9]
1884153480256
1884153480256


In [28]:
# copying array (shallow copy - copied array will be dependent on original array)

arr2 = arr1.view()

print(arr1)
print(arr2)

print(id(arr1))
print(id(arr2))

[7 6 7 8 9]
[7 6 7 8 9]
1884153480256
1884153482496


In [29]:
# copying array (deep copy - copied array don't get affected by change in original array)

arr2 = arr1.copy()

print(arr1)
print(arr2)

print(id(arr1))
print(id(arr2))

[7 6 7 8 9]
[7 6 7 8 9]
1884153480256
1884152879744
