Working with Matrix in Python

In [15]:
from numpy import*

arr1 = array([
             
              [1,2,3,4,5,6],
              [2,5,8,9,3,1]
    
              ])

print(arr1)

[[1 2 3 4 5 6]
 [2 5 8 9 3 1]]


In [16]:
print(arr1.dtype) #array type

int32


In [17]:
print(arr1.ndim) #dimentions

2


In [18]:
print(arr1.shape)

(2, 6)


In [19]:
print(arr1.size)

12


In [20]:
arr2 = arr1.flatten()

print(arr2)

[1 2 3 4 5 6 2 5 8 9 3 1]


In [24]:
arr3 = arr2.reshape(3,4)
print(arr3)

[[1 2 3 4]
 [5 6 2 5]
 [8 9 3 1]]


In [25]:
arr3 = arr2.reshape(2,2,3)
print(arr3)

[[[1 2 3]
  [4 5 6]]

 [[2 5 8]
  [9 3 1]]]


In [26]:
arr = array([
             
              [1,2,3,4],
              [5,6,7,8]
    
              ])
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


In [27]:
arr = array([
             
              [1,2,3,4],
              [5,6,7,8]
    
              ])
m = matrix(arr)
print(m)

[[1 2 3 4]
 [5 6 7 8]]


In [33]:
m = matrix('2 3 ; 4 5 ; 6 7; 8 9')
print(m)

[[2 3]
 [4 5]
 [6 7]
 [8 9]]


In [34]:
m = matrix('2 3 4 ; 5 6 7 ; 8 9 1')
print(m)

[[2 3 4]
 [5 6 7]
 [8 9 1]]


In [35]:
print(diagonal(m))

[2 6 1]


In [36]:
print(m.min())

1


In [37]:
print(m.max())

9


In [38]:
m1 = matrix('2 3 4 ; 5 6 7 ; 8 9 1')
m2 = matrix('8 7 6 ; 5 4 3 ; 2 1 9')

m3 = m1 + m2
print(m3)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [39]:
m1 = matrix('2 3 4 ; 5 6 7 ; 8 9 1')
m2 = matrix('8 7 6 ; 5 4 3 ; 2 1 9')

m3 = m1 * m2
print(m3)

[[ 39  30  57]
 [ 84  66 111]
 [111  93  84]]
